# Generated by Django 5.1.1 on 2024-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Название'),
        ),
    ]
